# Git Module
# Essential git and docker aliases

# Git aliases
alias g='noglob git'
alias ga='noglob git add'
alias gap='noglob git apply'
alias gapa='noglob git apply-patch'
alias gb='noglob git branch'
alias gba='noglob git branch -a'
alias gbd='noglob git branch -d'
alias gbr='noglob git branch -r'
alias gbs='noglob git branches'
alias gc='noglob git commit'
alias gca='noglob git commit --amend'
alias gcam='noglob git commit --amend --no-edit'
alias gcf='noglob git config --local'
alias gcl='noglob git clone'
alias gclean='noglob git clean -fd'
alias gcm='noglob git commit -m'
alias gco='noglob git checkout'
alias gcp='noglob git cherry-pick'
alias gcpa='noglob git cherry-pick --abort'
alias gdc='noglob git diff'
alias gd='noglob git daemon'
alias gds='noglob git describe'
alias gdt='noglob git dt'
alias gfa='noglob git fetch --all --prune'
alias gff='noglob git merge --ff-only'
alias gft='noglob git fetch'
alias gfu='noglob git reset --hard @{u}'
alias gfv='noglob git revert'
alias gg='noglob grep'
alias ggla='noglob git log --all --decorate --oneline --graph'
alias ggpl='noglob git log --all --decorate --oneline --graph --patch-with-stat'
alias ggs='noglob grep --show'
alias ggsup='noglob git submodule update --init --recursive'
alias ghh='noglob git log --all --graph --decorate'
alias ghu='noglob log --all --graph --decorate --oneline'
alias gia='noglob igignore --app'
alias gl='noglob log --all --decorate --oneline'
alias gla='noglob log --all --decorate --oneline --stat'
alias glg='noglob log --all --decorate --oneline --graph'
alias gld='noglob git ls-files -d'
alias glog='noglob log'
alias gm='noglob merge'
alias gma='noglob merge --abort'
alias gmom='noglob merge --octopus'
alias gms='noglob merge --squash'
alias gmt='noglob mergetool'
alias gmu='noglob merge --continue'
alias gp='noglob push'
alias gpl='noglob pull'
alias gpo='noglob push origin'
alias gpr='noglob pull --rebase --autostash --autostash'
alias gpra='noglob pull --rebase'
alias grp='noglob remote prune'
alias grr='noglob rebase'
alias gsh='noglob stash'
alias gsha='noglob log --all --decorate --oneline --graph --abbrev-commit'
alias gshup='noglob stash push -u'
alias gsm='noglob submodule'
alias gsp='noglob sparse-checkout'
alias gss='noglob show-stash'
alias gst='noglob status'
alias gsta='noglob stash save'
alias gstd='noglob stash drop'
alias gstu='noglob stash --include-untracked'
alias gsup='noglob superproject'
alias gsv='noglob svn'
alias gsw='noglob switch'
alias gta='noglob tag annotate'
alias gts='noglob tag show'
alias gtl='noglob tag -l'
alias gtv='noglob tag -v'
alias gtw='noglob tags --sort=v:refname'
alias gunignore='noglob git ls-files --others --exclude-standard'
alias gung='noglob unignore --remove-from=std'
alias gun='noglob unignore'
alias gwch='noglob whatch'
alias gwt='noglob worktree'
alias gwa='noglob worktree add'
alias gwd='noglob worktree all'
alias gwr='noglob worktree remove'
alias gws='noglob worktree list'

# Docker aliases
alias d='docker'
alias dc='docker-compose'
alias dcd='docker-compose down'
alias dce='docker-compose exec'
alias dcl='docker-compose logs'
alias dcl='docker-compose logs --follow'
alias dcp='docker-compose pull'
alias dcps='docker-compose ps'
alias dcr='docker-compose restart'
alias dcrl='docker-compose rm -f'
alias dcs='docker-compose stop'
alias dcstart='docker-compose start'
alias dcup='docker-compose up -d'
alias dcupd='docker-compose pull'
alias dps='docker ps'
alias dst='docker stop'
alias drun='docker run'
alias drm='docker rm'
alias drma='docker rmi'
alias drmi='docker images'
alias dstop='docker stop'
alias dstop='docker stop'
alias dvol='docker volume'

# Docker completion
if command -v docker >/dev/null 2>&1; then
    eval "$(docker completion zsh)"
fi
